'use client';

import dynamic from 'next/dynamic';
import type { ComponentType } from 'react';

// Lazy-load Player to avoid SSR (it uses browser APIs)
const Player = dynamic(
  () => import('@remotion/player').then((m) => m.Player),
  { ssr: false }
);

// Lazy-load compositions (all use default exports) to avoid pulling Remotion into the server bundle
const BlogStatCallout = dynamic(() => import('@/remotion/blog-visuals/BlogStatCallout'), { ssr: false });
const BlogDataComparison = dynamic(() => import('@/remotion/blog-visuals/BlogDataComparison'), { ssr: false });
const BlogTimeline = dynamic(() => import('@/remotion/blog-visuals/BlogTimeline'), { ssr: false });
const BlogMetricReveal = dynamic(() => import('@/remotion/blog-visuals/BlogMetricReveal'), { ssr: false });
const BlogProcessSteps = dynamic(() => import('@/remotion/blog-visuals/BlogProcessSteps'), { ssr: false });
// DynamicVisual — overwritten by the pipeline for the most recently generated post
const DynamicVisual = dynamic(() => import('@/remotion/blog-visuals/DynamicVisual'), { ssr: false });

interface CompositionMeta {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  component: ComponentType<any>;
  durationInFrames: number;
  fps: number;
  width: number;
  height: number;
}

const COMPOSITION_MAP: Record<string, CompositionMeta> = {
  BlogStatCallout: { component: BlogStatCallout, durationInFrames: 240, fps: 30, width: 1280, height: 720 },
  BlogDataComparison: { component: BlogDataComparison, durationInFrames: 300, fps: 30, width: 1280, height: 720 },
  BlogTimeline: { component: BlogTimeline, durationInFrames: 360, fps: 30, width: 1280, height: 720 },
  BlogMetricReveal: { component: BlogMetricReveal, durationInFrames: 240, fps: 30, width: 1280, height: 720 },
  BlogProcessSteps: { component: BlogProcessSteps, durationInFrames: 300, fps: 30, width: 1280, height: 720 },
  // AI-generated bespoke composition — reflects whatever was last generated by the pipeline
  DynamicVisual: { component: DynamicVisual, durationInFrames: 240, fps: 30, width: 1280, height: 720 },
};

interface Props {
  compositionId: string;
  inputProps: Record<string, unknown>;
}

export function BlogVideoPlayer({ compositionId, inputProps }: Props) {
  const meta = COMPOSITION_MAP[compositionId];
  if (!meta) return null;

  return (
    <div
      style={{
        margin: '2rem 0',
        borderRadius: '6px',
        overflow: 'hidden',
        border: '1px solid var(--border-subtle)',
        background: '#0a0908',
        aspectRatio: '16/9',
        maxWidth: '100%',
      }}
    >
      <Player
        component={meta.component}
        durationInFrames={meta.durationInFrames}
        fps={meta.fps}
        compositionWidth={meta.width}
        compositionHeight={meta.height}
        inputProps={inputProps}
        style={{ width: '100%', height: '100%' }}
        controls
        loop
        autoPlay={false}
      />
    </div>
  );
}
